#!/bin/bash

# upload test readings
curl -X POST -H "Content-Type: application/json" -d '{"h" : "65", "t" : "21"}' http://localhost:8080/arduino

# retrieve test readings
curl -X GET http://localhost:8080/arduino

